### ISSUE TITLE
Warnings with React 18

### ISSUE THREAD

**Issue by dhruvin25799** [cookpete/react-player#1439]
#### Current Behavior
Getting infinite warnings could not call getDuration, getCurrentTime, getVideoLoadedFraction on React 18.
This is only happening when React 18 with createRoot is used.
The app works fine, the video works fine only these infinite warnings are the issue.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/47236093/163718134-de0fd95d-278e-4a24-8fd3-4885fe76193c.png">

#### Expected Behavior
Shouldn't have any warnings or any function calls.

#### Steps to Reproduce

1. Codesandbox Link : https://codesandbox.io/s/snowy-field-u9fugp?file=/src/App.js

#### Environment
- React 18 with createRoot

**Comment by cookpete** [comment]
It looks like some change in React 18 is messing up the [`callPlayer`](https://github.com/cookpete/react-player/blob/646e62eb0ef1c3b7e980b55f416f7d8845482af7/src/utils.js#L130-L144) util.  If I `console.log(this.player)` in the util I get this output:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1926029/163729826-58ca1a87-2a43-41b6-bd9d-a8367a91307e.png">

Notice the target iframe changes from `widget2` (correct) to `widget4` (which doesn’t exist). 

Looking back, the implementation of `callPlayer` is strange and probably very brittle.

**Comment by cookpete** [comment]
Looks like this issue also stops happening if you remove `<StrictMode>`

**Comment by juanfraherrero** [comment]
> Looks like this issue also stops happening if you remove `<StrictMode>`

Sorry, from where i should remove <StrictMode>?

**Comment by wimpykatana** [comment]
> > Looks like this issue also stops happening if you remove `<StrictMode>`
> 
> Sorry, from where i should remove `<StrictMode>`?

You can find it inside your index.js

**Comment by cookpete** [comment]
Looks like this is fixed in React 18.1

**Comment by chochihim** [comment]
@cookpete I am using React 18.1 but still getting these infinite warnings. FYI I am also using Next.js 12.1.6

**Comment by cookpete** [comment]
Yep you’re right, sorry. I was confused with a different issue.

**Comment by manishsharma004** [comment]
There seems to be an issue with double loading of Youtube api, which overrides the `Youtube.player` value.

Only first `YT.Player` instance get the updates recieved from iframe messages for update apiInterface that adds the getDuration, getCurrentTime etc. methods. Stopping the multiple load for a url solves the issue. @cookpete added a [PR](https://github.com/cookpete/react-player/pull/1450) which may or may not be an ideal solution to issue.

**Comment by lehnerpat** [comment]
As a temporary workaround, you can use the patch below to apply @manishsharma004's changes from #1450 to your locally-installed NPM package.

**How to apply the fix manually / one-time:**
* Save the patchfile contents below to a file `Player.js.patch` (note: filename and location don't matter, but I'll use this as an example)
* In your project, run `patch -i Player.js.patch node_modules/react-player/lib/Player.js` (if your `Player.js.patch` file is located somewhere else, use the right path here)

**How to apply this fix with a `postinstall` script** (useful if your project is built by a CI server or you collaborate with other people):
* Save the patchfile contents below to a file `Player.js.patch` and **check it into your repo**
* in your `package.json`, add a "postinstall" script:
    ```json
. . .
"scripts": {
  . . .
  "postinstall": "patch -i Player.js.patch node_modules/react-player/lib/Player.js -N || true"
},
. . .
```
* adjust the path of the patch file as needed
* Note: the `-N` argument and the `|| true` make sure that the postinstall script doesn't fail if the patch is already applied (i.e. if `npm install`/`yarn install` is being run when `react-player` is already installed)
* Be sure to remove this again when a fixed version of `react-player` is released and you update to it :)


----

```patch
--- node_modules/react-player/lib/Player.js	2022-05-07 18:04:18.000000000 +0200
+++ node_modules/react-player/lib/Player.js	2022-05-07 18:04:01.000000000 +0200
@@ -82,7 +82,10 @@
     _defineProperty(_assertThisInitialized(_this), "handlePlayerMount", function (player) {
       _this.player = player;

-      _this.player.load(_this.props.url);
+      if (!_this.loaded?.[_this.props.url]) {
+        _this.player.load(_this.props.url);
+        _this.loaded = { [_this.props.url]: true };
+      }

       _this.progress();
     });
@@ -288,7 +291,10 @@
         this.isLoading = true;
         this.startOnPlay = true;
         this.onDurationCalled = false;
-        this.player.load(url, this.isReady);
+        if (!this.loaded?.[url]) {
+          this.player.load(url, this.isReady)
+          this.loaded = { [url]: true }
+        }
       }

       if (!prevProps.playing && playing && !this.isPlaying) {

```

**Comment by manishsharma004** [comment]
Thanks @lehnerpat for the detailed guide on patch, however I wouldn't recommend patching your production code with a changes from someone who isn't a developer on the project(me) until it gets reviewed by project developers. So, I would suggest patching only if there's no other way.

**Comment by lehnerpat** [comment]
Yup, absolutely valid point!

I just needed a workaround for the time being and built it so I thought I'd share :)

>

**Comment by cookpete** [comment]
This should now be fixed, as of `2.10.1`
