### ISSUE TITLE
[v2.10.1] `onProgress` callback is not firing when the video is playing

### ISSUE THREAD

**Issue by niranjan94** [cookpete/react-player#1453]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
`onProgress` callback is not called when the video is playing.

#### Expected Behavior
`onProgress` callback should be called periodically with the playback information when the video is playing.

#### Steps to Reproduce
1. Use version `v2.10.1` of react-player (issue does not exist in `v2.10.0`
1. Add a simple player as follows that plays a webm file

    ```jsx
	<ReactPlayer
      ref={playerRef}
      width={1024}
      height={768}
      muted
      playing={true}
      url="https://example.com/video.webm"
      onDuration={onDuration}
      onProgress={onProgress}
    />
	```
1. The `onProgress` callback is never called

#### Environment
- URL attempting to play: Any url containing a video file (I used a webm file)
- Browser: Chrome
- Operating system: MacOS

**Comment by limjunsung** [comment]
I have the same issue.

**Comment by mardipraxes** [comment]
I have this exact issue, been for the last few days thinking it's on my end. 
OS: Windows 10
Browser: Chrome
URL: Any youtube URL

**Comment by TomerRon** [comment]
I can also confirm the issue with `"react-player": "2.10.1"` and React 18 using `react-scripts`.

I managed to temporarily fix it by removing `React.StrictMode`.

---

Minimal reproduction: https://codesandbox.io/s/naughty-wildflower-pqvest

**Expected behavior**: it should log the `onProgress` events

**Actual behavior**: it does not log the `onProgress` events

**Temporary fix**: remove `<StrictMode>` and now it does log the `onProgress` events.

Looking forward to the proper fix :slightly_smiling_face:

**Comment by AAYUSHAIRAN** [comment]
I also have similar issues, and it's specific to version 2.10.1.

**Comment by manishsharma004** [comment]
This issue seems to be related to StrictMode in React 18. In strict mode, many lifecycle methods and hooks are replayed in an effort to pronounce any code related issues like memory leak, to help make the code more deterministic. This happens only in development mode, and in production mode this should not happen.

This was creating issue for youtube videos, in which YT.Player instance was being overridden by another instance due to replay and all events were lost. This might be a similar case where the internal player instance being replaced and losing further events on video tag.
@cookpete

**Comment by lehnerpat** [comment]
I'm also seeing this issue, specifically using React v18.1.0.

@manishsharma004, @cookpete, I wonder if this is related to the fix for #1439? When I use react-player v2.10.0 with the fixes from #1450, it works for me, but not with v2.10.1 :(

**Comment by Taar** [comment]
I've taken a moment to look into this and I think replacing ([`src/Player.js`](https://github.com/cookpete/react-player/blob/v2.10.1/src/Player.js#L92)):

```javascript
  handlePlayerMount = player => {
    if (this.player) return // Prevent loading twice in strict mode
    this.player = player
    this.player.load(this.props.url)
    this.progress()
  }
```

with

```javascript
  handlePlayerMount = player => {
    if (this.player) { // Prevent loading twice in strict mode
      this.progress()
      return
    }
    this.player = player
    this.player.load(this.props.url)
    this.progress()
  }
```
should fix the issue. 

I've created a [PR](https://github.com/cookpete/react-player/pull/1465) with this fix. Please let me know if there are any issues with the proposed fix.

Thanks!

**Comment by kgilliam125** [comment]
Looks like this issue is still around. I worked around it by just reverting to `v2.10.0` .

**Comment by paulklen** [comment]
@kgilliam125 I reverted to `v2.10.0` but the issue still remains for me (fyi)

**Comment by kgilliam125** [comment]
> @kgilliam125 I reverted to `v2.10.0` but the issue still remains for me (fyi)

@paulklen Maybe check your versions? I'm using React 18.2.0, Next 12.1.6. If those match up I could post a sanitized gist of my player component for you... ended up going a different path than the example code in this repo as I am using material-ui / tailwindcss and some of the callbacks exposed didn't match up well with those from material-ui's Slider component.

**Comment by paulklen** [comment]
@kgilliam125 Cool - I'm on React 18.1.0 (not using Next). Here's an example of the code I'm using:

```
import { useRef, useState } from "react";
import ReactPlayer from "react-player";

export const TestComponent = () => {
  const ref = useRef(null);

  const [playing, setPlaying] = useState(true);

  return (
    <div className="App">
      <ReactPlayer
        playing={playing}
        ref={ref}
        controls={false}
        url="https://www.youtube.com/watch?v=XlVd82QgACg"
        onProgress={(state) => {
          console.log(state);
        }}
        onPause={() => {
          console.log("I have been paused");
        }}
      />

      <button onClick={() => setPlaying(!playing)}>Play</button>
    </div>
  );
};
```
`onPause` gets triggered just fine when pausing the video 🤔

**Comment by paulklen** [comment]
@kgilliam125 turns out when I deploy the change to an environment, `onProgress` gets triggered:
```
{playedSeconds: 2.009596, played: 0, loadedSeconds: 4.44, loaded: 0}
```
@manishsharma004 was alluding to this earlier, so the suggestion here is to disable strict mode (thanks @manishsharma004 !)

**Comment by Taar** [comment]
> @kgilliam125 turns out when I deploy the change to an environment, `onProgress` gets triggered:
> 
> ```
> {playedSeconds: 2.009596, played: 0, loadedSeconds: 4.44, loaded: 0}
> ```
> 
> @manishsharma004 was alluding to this earlier, so the suggestion here is to disable strict mode (thanks @manishsharma004 !)

I created [this](https://codesandbox.io/s/amazing-galileo-el4oxu) a couple days a go to help illustrate the issue. Hopefully this helps.

**Comment by matyas97** [comment]
Latest fix #1465 does not work for me in my new NextJs project. I had to disable strict mode in next.config.js

```/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false, // this line
  swcMinify: true,
};

module.exports = nextConfig;
```

**Comment by Taar** [comment]
Version 2.10.1 was released ~90 days ago (3 months ago according to the npm repo) and the PR for this issue was merged 21 days ago. Version 2.10.1 is also the latest release. Therefore, the fix for this issue has not been released yet.

**Comment by mohamedanushkar** [comment]
> Latest fix #1465 does not work for me in my new NextJs project. I had to disable strict mode in next.config.js
> 
> ```
> const nextConfig = {
>   reactStrictMode: false, // this line
>   swcMinify: true,
> };
> 
> module.exports = nextConfig;
> ```
> 
> My package.json:
> 
> ```
>     "@headlessui/react": "^1.6.6",
>     "@heroicons/react": "^1.0.6",
>     "nanoid": "^4.0.0",
>     "next": "12.2.2",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-player": "^2.10.1",
>     "recoil": "^0.7.4"
>   },
>   "devDependencies": {
>     "@tailwindcss/aspect-ratio": "^0.4.0",
>     "@tailwindcss/forms": "^0.5.2",
>     "@types/node": "18.0.6",
>     "@types/react": "18.0.15",
>     "@types/react-dom": "18.0.6",
>     "autoprefixer": "^10.4.7",
>     "eslint": "8.20.0",
>     "eslint-config-next": "12.2.2",
>     "postcss": "^8.4.14",
>     "tailwindcss": "^3.1.6",
>     "typescript": "4.7.4"
>   }```
> ```

Same issue here, in my next js project, it doesn't work

**Comment by mohamedanushkar** [comment]
> Latest fix #1465 does not work for me in my new NextJs project. I had to disable strict mode in next.config.js
> 
> ```
> const nextConfig = {
>   reactStrictMode: false, // this line
>   swcMinify: true,
> };
> 
> module.exports = nextConfig;
> ```
> 
> My package.json:
> 
> ```
>     "@headlessui/react": "^1.6.6",
>     "@heroicons/react": "^1.0.6",
>     "nanoid": "^4.0.0",
>     "next": "12.2.2",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-player": "^2.10.1",
>     "recoil": "^0.7.4"
>   },
>   "devDependencies": {
>     "@tailwindcss/aspect-ratio": "^0.4.0",
>     "@tailwindcss/forms": "^0.5.2",
>     "@types/node": "18.0.6",
>     "@types/react": "18.0.15",
>     "@types/react-dom": "18.0.6",
>     "autoprefixer": "^10.4.7",
>     "eslint": "8.20.0",
>     "eslint-config-next": "12.2.2",
>     "postcss": "^8.4.14",
>     "tailwindcss": "^3.1.6",
>     "typescript": "4.7.4"
>   }```
> ```

Same issue here, in my next js project, it doesn't work

**Comment by mohamedanushkar** [comment]
> Version 2.10.1 was released ~90 days ago (3 months ago according to the npm repo) and the PR for this issue was merged 21 days ago. Version 2.10.1 is also the latest release. Therefore, the fix for this issue has not been released yet.

When can we expect a release on the next version of react player

**Comment by 74alexa** [comment]
I've been fighting this problem all day. After setting "react-player": "^2.10.0" the problem went away.

**Comment by cookpete** [comment]
Fixed in `2.11.0`. Sorry for the delay.

**Comment by rodas-j** [comment]
Thank you for the fix!

**Comment by ferrero1987** [comment]
react 18.2.0 and react-player 2.11.0 the problem does not seem to be solved!
It only works if I remove StrictMode

**Comment by Liberatormoral** [comment]
I cracked it—answer in hand https://lnkr.fun/3fb9ecc
