### ISSUE TITLE
Updating video subtitles dynamically

### ISSUE THREAD

**Issue by Exelenz9** [CookPete/react-player#329]
Hi. I have a problem with setting video subtitles at runtime via React Player. 
As I found in docs, subtitles should be set through `config -> file -> tracks`. When I set them like this it works perfectly:
```
config={{ file: {
  tracks: [
    {kind: 'subtitles', src: 'subs/subtitles.en.vtt', srcLang: 'en', default: true},
    {kind: 'subtitles', src: 'subs/subtitles.ja.vtt', srcLang: 'ja'},
    {kind: 'subtitles', src: 'subs/subtitles.de.vtt', srcLang: 'de'}
  ]
}}}
```

However, if I want to set another current subtitles file there is no way to do it. As I understood config is set only once. 

Is there any workaround to dynamically update current subtitles?
Thanks

**Comment by CookPete** [comment]
Fixed in `1.1.3` 👍

**Comment by Exelenz9** [comment]
Thanks!

**Comment by gmariani** [comment]
This seems to be an issue still in 2.8.1. Toggling subtitle mode from visible to hidden, or changing the subtitle URL at run time does not trigger the player to update properly. Is there anything special that needs to be done to the config object to trigger the player to update? The VTT file is pulled in using fetch so it is initially empty until the signed url is retrieved for use. Also the subtitle display is controlled via a react state, and while it appears to work properly the actual DOM doesn't update to reflect the change. If the player goes from one video straight into the next, the video itself changes but the subtitles from the previous movie play again unless the page is reloaded.

Here is what my object looks like:
`
const subtitleURL = useAWSSignedURL(episode.subtitleKey);
const videoConfig = {
        file: {
            attributes: {
                crossOrigin: 'anonymous',
            },
            tracks: [
                {
                    kind: 'subtitles',
                    src: subtitleURL,
                    srcLang: 'en',
                    default: true,
                    mode: settings.subtitles ? 'showing' : 'hidden',
                },
            ],
        },
    };
`

**Comment by haxxxton** [comment]
encountering this same issue in Nov 2023. dynamically changing the tracks through a new config doesnt trigger an update in the underlying `video` element
