### ISSUE TITLE
Help me out setting up the test env. properly

### ISSUE THREAD

**Issue by denisflorkin** [CookPete/react-player#63]
Hello, I'm extremely new to testing and I'm having an issue when running the tests, it's seems the tests runs correctly but then at the end I get this 'error' : 
`19 05 2016 15:44:19.522:WARN [Firefox 46.0.0 (Mac OS X 10.10.0)]: Disconnected (1 times), because no message in 10000 ms.`
It happend even when I run the test cmd. on the untouched code from the repo, that's why I think my 'environment' is to blame.

It seems similar to this [SO question](http://stackoverflow.com/questions/23667102/disconnected-1-times-because-no-message-in-10000-ms-using-karma-jasmine)

Except that if I understand correctly, webpack is used here and it's correctly referenced in the karma conf.
This is the list of the relevant package that are globally installed on my machine : 
webpack@1.13.0, karma-cli@0.1.2

npm@2.10.1
node@5.6.0

So what could it be? is there maybe some package that I should have installed globally and I didn't... ?
I'd appreciate any help, tips, boost on where to look harder...

full tests stdout : 
```
Mac-Pro-de-Denis:react-player denisflorkin$ npm run test

> react-player@0.5.8 test /Volumes/DF/denisflorkin/Projects/df-react-player/react-player
> karma start test/karma.config.js


START:
19 05 2016 15:44:06.338:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
19 05 2016 15:44:06.364:INFO [launcher]: Starting browser Chrome
19 05 2016 15:44:06.374:INFO [launcher]: Starting browser Firefox
19 05 2016 15:44:07.508:INFO [Chrome 50.0.2661 (Mac OS X 10.10.3)]: Connected on socket /#szuh4egBZGmmBcXPAAAA with id 27122343
19 05 2016 15:44:09.213:INFO [Firefox 46.0.0 (Mac OS X 10.10.0)]: Connected on socket /#72RocFtPTJRPn0rrAAAB with id 52663611
19 05 2016 15:44:19.522:WARN [Firefox 46.0.0 (Mac OS X 10.10.0)]: Disconnected (1 times), because no message in 10000 ms.

Finished in 29.522 secs / 19.303 secs


npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.6.0
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! react-player@0.5.8 test: `karma start test/karma.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-player@0.5.8 test script 'karma start test/karma.config.js'.
npm ERR! This is most likely a problem with the react-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start test/karma.config.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/DF/denisflorkin/Projects/df-react-player/react-player/npm-debug.log

```

npm-debug.log :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.10.1
3 info using node@v5.6.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest react-player@0.5.8
6 info test react-player@0.5.8
7 verbose unsafe-perm in lifecycle true
8 info react-player@0.5.8 Failed to exec test script
9 verbose stack Error: react-player@0.5.8 test: `karma start test/karma.config.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at EventEmitter.emit (events.js:185:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at ChildProcess.emit (events.js:185:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-player@0.5.8
11 verbose cwd /Volumes/DF/denisflorkin/Projects/df-react-player/react-player
12 error Darwin 14.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
14 error node v5.6.0
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error react-player@0.5.8 test: `karma start test/karma.config.js`
17 error Exit status 1
18 error Failed at the react-player@0.5.8 test script 'karma start test/karma.config.js'.
18 error This is most likely a problem with the react-player package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     karma start test/karma.config.js
18 error You can get their info via:
18 error     npm owner ls react-player
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by CookPete** [comment]
I guess the obvious thing to start with would be to ensure all latest package versions. I've just pushed a commit to bump all package versions, so `git pull` and `npm install` to see if that helps.

Testing with karma has always been a bit dodgy for me, mainly just because the sheer amount of third party SDKs and players can be quite unreliable and inconsistent. Firstly I would remove `Firefox` from [here](https://github.com/CookPete/react-player/blob/master/test/karma.config.js#L6) to test with Chrome only (which seems the most reliable) to make sure things work ok at least in Chrome.

You can also try `npm run test -- --no-single-run` which will keep the browsers open for you to refresh the tests, inspect stuff, open console, etc.

My last attempt would be to increase the `onPause` timeout [here](https://github.com/CookPete/react-player/blob/master/test/karma/ReactPlayer.js#L38), which may help.

**Comment by denisflorkin** [comment]
Ok thanks fo the response. I still can't get get the tests running in ff but removing it from the config and use chrome only will do for now :)

**Comment by CookPete** [comment]
I'll close this for now. Feel free to reopen if something comes up again, but running tests with karma + react + various third party scripts/iframes has always been inconsistent and buggy for me.
