### ISSUE TITLE
Seeking behavior doesn't seem to work on demo page.

### ISSUE THREAD

**Issue by ralusek** [CookPete/react-player#867]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
On this demo page:
https://cookpete.com/react-player/
The seek position slider will update correctly with the current timestamp, but clicking on a position along the slider will temporarily move the slider to that position, fail to seek the video accordingly, and jump back to the position corresponding with the player's position. I tried this with YouTube, Vimeo, and a few others, and they all demonstrated the same behavior.

#### Expected Behavior
I expect seeking to a position to have the corresponding video playback also seek to the same position.

#### Steps to Reproduce
1.) go to https://cookpete.com/react-player/
2.) click on Youtube Test A
3.) click play on the video, wait for playback to begin
4.) note position on bar titled "Seek" updating correctly, corresponding with position in playback
5.) attempt to move the seek marker (not in the YouTube video, but react-player UI) to a desired position
6.) note that the video does not seek to this position, and the playback marker jumps back to the video playback position

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=oUFJJNQGwhk
- Browser: Chrome
- Operating system: Mac OS
- Demo page: https://cookpete.com/react-player/

**Comment by ralusek** [comment]
@CookPete I fixed this issue here:
https://github.com/CookPete/react-player/pull/868

All tests/lint passing, I recommend merging it because a lot of critical behavior is resolved by this change.

**Comment by CookPete** [comment]
Fixed in `v2.0.1`

**Comment by omerkhan8** [comment]
working fine with youtube, but this is still happening in vimeo.. any help?

**Comment by cagarweyne** [comment]
> Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.
> 
> #### Current Behavior
> On this demo page:
> https://cookpete.com/react-player/
> The seek position slider will update correctly with the current timestamp, but clicking on a position along the slider will temporarily move the slider to that position, fail to seek the video accordingly, and jump back to the position corresponding with the player's position. I tried this with YouTube, Vimeo, and a few others, and they all demonstrated the same behavior.
> 
> #### Expected Behavior
> I expect seeking to a position to have the corresponding video playback also seek to the same position.
> 
> #### Steps to Reproduce
> 1.) go to https://cookpete.com/react-player/
> 2.) click on Youtube Test A
> 3.) click play on the video, wait for playback to begin
> 4.) note position on bar titled "Seek" updating correctly, corresponding with position in playback
> 5.) attempt to move the seek marker (not in the YouTube video, but react-player UI) to a desired position
> 6.) note that the video does not seek to this position, and the playback marker jumps back to the video playback position
> 
> #### Environment
> * URL attempting to play: https://www.youtube.com/watch?v=oUFJJNQGwhk
> * Browser: Chrome
> * Operating system: Mac OS
> * Demo page: https://cookpete.com/react-player/
> 
> #### Other Information

I know on mobile there are some issues with video etc. But the seek does not work on mobile, it's the same as the issue described above. Is this a know issue?
